// @ts-nocheck
import React, { useState } from 'react';
import { KeyRound, Eye, EyeOff, Copy, Check, ShieldCheck } from 'lucide-react';
import { maskCode } from '../utils/auth';

interface AccessCodeCardProps {
  label: string;
  code: string;
  ownerName?: string;
  note?: string;
  accent?: 'emerald' | 'purple' | 'amber' | 'blue';
}

const ACCENTS: Record<string, string> = {
  emerald: 'from-emerald-500/15 to-emerald-500/5 border-emerald-500/40 text-emerald-500',
  purple: 'from-purple-500/15 to-purple-500/5 border-purple-500/40 text-purple-500',
  amber: 'from-amber-500/15 to-amber-500/5 border-amber-500/40 text-amber-500',
  blue: 'from-blue-500/15 to-blue-500/5 border-blue-500/40 text-blue-500',
};

export const AccessCodeCard: React.FC<AccessCodeCardProps> = ({
  label,
  code,
  ownerName,
  note,
  accent = 'emerald',
}) => {
  const [shown, setShown] = useState(false);
  const [copied, setCopied] = useState(false);

  const copy = async () => {
    try {
      await navigator.clipboard.writeText(code);
      setCopied(true);
      setTimeout(() => setCopied(false), 1600);
    } catch {
      /* clipboard unavailable */
    }
  };

  return (
    <div className={`rounded-3xl border bg-gradient-to-br p-4 sm:p-5 ${ACCENTS[accent]} lk-motif`}>
      <div className="flex items-center gap-2 mb-2">
        <KeyRound className="w-4 h-4" />
        <h3 className="text-xs font-black uppercase tracking-wider">{label}</h3>
      </div>

      {ownerName && (
        <p className="text-[11px] font-bold opacity-80 mb-2">{ownerName}</p>
      )}

      <div className="flex flex-wrap items-center gap-2">
        <code className="font-mono text-xl sm:text-2xl font-black tracking-[0.2em] px-3 py-1.5 rounded-xl bg-slate-950/70 text-white border border-white/10">
          {shown ? code : maskCode(code)}
        </code>
        <button
          type="button"
          onClick={() => setShown(s => !s)}
          className="flex items-center gap-1 text-[11px] font-black px-3 py-2 rounded-xl bg-slate-900 text-white hover:bg-slate-800 transition"
        >
          {shown ? <EyeOff className="w-3.5 h-3.5" /> : <Eye className="w-3.5 h-3.5" />}
          {shown ? 'Hide' : 'Show'}
        </button>
        <button
          type="button"
          onClick={copy}
          className="flex items-center gap-1 text-[11px] font-black px-3 py-2 rounded-xl bg-slate-900 text-white hover:bg-slate-800 transition"
        >
          {copied ? <Check className="w-3.5 h-3.5" /> : <Copy className="w-3.5 h-3.5" />}
          {copied ? 'Copied' : 'Copy'}
        </button>
      </div>

      <p className="mt-3 text-[10px] font-bold opacity-75 flex items-start gap-1.5">
        <ShieldCheck className="w-3.5 h-3.5 shrink-0 mt-px" />
        <span>{note || 'This code is generated by the system and visible only to you. Never share it with other students, parents or teachers.'}</span>
      </p>
    </div>
  );
};
